module.exports = {
  // Executables
  ON_INIT: 'ON_INIT',
  SET_LOADING: 'SET_LOADING',
  LOAD_ASSETS: 'LOAD_ASSETS',
  LOAD_ASSETS_DONE: 'LOAD_ASSETS_DONE',
  LOAD_SOUNDS: 'LOAD_SOUNDS',
  LOAD_SOUNDS_DONE: 'LOAD_SOUNDS_DONE',
  GAME_READY: 'GAME_READY',

  // Session Constants
  SET_DEVELOPER_MODE: 'SET_DEVELOPER_MODE',

  // UI Constants
  SET_DIMENSIONS: 'SET_DIMENSIONS',
}